### ISSUE TITLE
[BUG] Error On Mac

### ISSUE THREAD

**Issue by deepou** [xenova/chat-downloader#132]
chat-downloader USERNAME$ chat_downloader https://www.youtube.com/watch?v=_wOHPi9-opw
Traceback (most recent call last):
  File "/usr/local/bin/chat_downloader", line 11, in <module>
    load_entry_point('chat-downloader==0.1.10', 'console_scripts', 'chat_downloader')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/chat_downloader-0.1.10-py2.7.egg/chat_downloader/__init__.py", line 3, in <module>
    from .chat_downloader import (
  File "/Library/Python/2.7/site-packages/chat_downloader-0.1.10-py2.7.egg/chat_downloader/chat_downloader.py", line 76
    log('debug', f'Python version: {sys.version}')
                                                ^
SyntaxError: invalid syntax

**Comment by xenova** [comment]
Hi there. This is an issue because you are using python2.7 - which reached it's end-of-life ~2 years ago (https://www.python.org/doc/sunset-python-2/)

So, you will need to use python3 (either by using `python3` in terminal, or by updating your current version)

Assuming you have python3 installed, you should be able to install and run using these commands:

Install:
`pip3 install chat-downloader`

Run:
`python3 -m chat_downloader -h`

**Comment by deepou** [comment]
Thank you, worked out perfectly!
