### ISSUE TITLE
[BUG] chat_downloader.errors.ParsingError

### ISSUE THREAD

**Issue by tinglee875** [xenova/chat-downloader#135]
## Basic information
- Program version: v0.1.10
- Python version: Python 3.6.5
- Operating system:Ubuntu 18.04.1 LTS

## Describe the bug
    raise ParsingError: Unable to parse initial video data when I try to get live chat messages
## Command/Code used
url = "https://www.youtube.com/watch?v=EqUKTaxHiEE"
chat = ChatDownloader().get_chat(url)

### Otherwise, if using the python module, provide the following:

1. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):
```python
# python code
from chat_downloader import ChatDownloader
url = "https://www.youtube.com/watch?v=EqUKTaxHiEE"
chat = ChatDownloader().get_chat(url)
```

2. Output, traceback or other information relating to the bug:
```
Traceback (most recent call last):
  File "yt.py", line 297, in <module>
    main()
  File "yt.py", line 294, in main
    get_all()
  File "yt.py", line 280, in get_all
    chat = ChatDownloader().get_chat(url)
  File "/home/qqqqq3202390739/.local/lib/python3.6/site-packages/chat_downloader/chat_downloader.py", line 224, in get_chat
    chat = get_chat(match, params)
  File "/home/qqqqq3202390739/.local/lib/python3.6/site-packages/chat_downloader/sites/youtube.py", line 2078, in _get_chat_by_video_id
    return self.get_chat_by_video_id(match.group('id'), params)
  File "/home/qqqqq3202390739/.local/lib/python3.6/site-packages/chat_downloader/sites/youtube.py", line 2069, in get_chat_by_video_id
    initial_info, ytcfg = self._get_initial_video_info(video_id, params)
  File "/home/qqqqq3202390739/.local/lib/python3.6/site-packages/chat_downloader/sites/youtube.py", line 1453, in _get_initial_video_info
    video_id, params, video_type)
  File "/home/qqqqq3202390739/.local/lib/python3.6/site-packages/chat_downloader/sites/youtube.py", line 1378, in _parse_video_data
    original_url, params)
  File "/home/qqqqq3202390739/.local/lib/python3.6/site-packages/chat_downloader/sites/youtube.py", line 1349, in _get_initial_info
    raise ParsingError(f'Unable to parse initial video data')
chat_downloader.errors.ParsingError: Unable to parse initial video data
[output or description]
```

## Expected behavior
there's a live chat box for the video so I expect it should return live chat messages

**Comment by tinglee875** [comment]
Oh sorry it's a settings problem of my system.
