### ISSUE TITLE
[BUG] "👍🏼👍🏼" in chat crashes the program

### ISSUE THREAD

**Issue by atnbueno** [xenova/chat-downloader#138]
## Basic information
- Program version: 0.0.9
- Python version: 3.10.2
- Operating system: Windows 10.0.19041.1415

## Describe the bug
A "👍🏼👍🏼" in the chat crashes the program

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_replay_downloader -v https://www.youtube.com/watch?v=KXlgRVFHhHo --format_file csv -o livechat.csv
```
2. Output from the above command:
```
[DEBUG] Python version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
[DEBUG] Program version: 0.0.9
[INFO] Site: youtube.com
[DEBUG] Parameters: {'url': 'https://www.youtube.com/watch?v=KXlgRVFHhHo', 'start_time': None, 'end_time': None, 'max_attempts': 15, 'retry_timeout': None, 'timeout': None, 'max_messages': None, 'logging': 'debug', 'pause_on_debug': False, 'inactivity_timeout': None, 'message_groups': ['messages'], 'message_types': None, 'format': 'youtube', 'format_file': None, 'chat_type': 'live', 'message_receive_timeout': 0.1, 'buffer_size': 4096}
[DEBUG] Starting new HTTPS connection (1): www.youtube.com:443
[DEBUG] https://www.youtube.com:443 "GET /watch?v=KXlgRVFHhHo HTTP/1.1" 200 None
[DEBUG] Chat information: {'chat': <generator object YouTubeChatDownloader._get_chat_messages at 0x0000017A10E5BA00>, 'title': 'Automating pro podcasters’ Mac workflows (w/ Jason Snell and Dan Moren)', 'duration': 5507, 'is_live': False, 'start_time': 1643744523932762.0, 'site': <chat_replay_downloader.sites.youtube.YouTubeChatDownloader object at 0x0000017A11329AE0>, 'format': <function ChatDownloader.get_chat.<locals>.<lambda> at 0x0000017A11333640>}
[INFO] Retrieving chat for "Automating pro podcasters’ Mac workflows (w/ Jason Snell and Dan Moren)".
[DEBUG] https://www.youtube.com:443 "GET /live_chat_replay?continuation=op2w0wRgGlhDaWtxSndvWVZVTmtkRVJWYUZZeWNWbFBjRFpFTjFoMWRtbEVUMHRuRWd0TFdHeG5VbFpHU0doSWJ4b1Q2cWpkdVFFTkNndExXR3huVWxaR1NHaElieUFCQAFyAggB HTTP/1.1" 200 None
-3:12 | Jarrod Blundy: Howdy! Been keenly following this saga, so looking forward to the discussion!
-0:31 | Jean MacDonald: Good morning, or afternoon or whatever :slightly_smiling_face:
1:04 | (Owner) Matthew Cassinelli: Welcome!
1:21 | Rowan Strang: Awesome! We
1:23 | (Owner) Matthew Cassinelli: Let me know if there's any audio or video issues!
1:42 | Rowan Strang: Very excited to follow this chat
2:08 | Clackamas coot: The sound is perfect!
2:25 | Mike Hendley: Great idea doing this
8:31 | Antonio Bueno: Oh. God. That “POSIX file … as alias” is causing me flashbacks :face_with_tears_of_joy:
16:35 | Mike Hendley: Do all of you edit on desktop? Anyone using Ferrite regularly?
18:39 | philodygmn: Exactitude is maybe not always necessary, but definitely often much appreciated: imprecise scroll position, for example, in Notes on iPad drives me NUTS.
20:22 | Chris O: @Mike Hendley I use Ferrite for editing...
20:40 | Chris O: also for note taking while recording... so I modified this idea a bit to key off an RTF file that is created at the time I start the recording...
26:20 | Antonio Bueno: HH:mm:SYS
26:31 | Antonio Bueno: HH:mm:ss
28:07 | Antonio Bueno: Also, “Calculate Expression” only works with periods :downcast_face_with_sweat:
28:45 | philodygmn: Surfacing undocumented stuff like this is why we follow you folks:grinning_face: t/y!
30:11 | philodygmn: But yes, absolutely, Apple should document it:grinning_face_with_sweat:
[DEBUG] Session closed.
Traceback (most recent call last):
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\Scripts\chat_replay_downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_replay_downloader\cli.py", line 229, in main
    for message in chat:
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_replay_downloader\sites\common.py", line 87, in __iter__
    for item in self.chat:
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_replay_downloader\sites\youtube.py", line 1014, in _get_chat_messages
    data = self._parse_item(original_item, data)
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_replay_downloader\sites\youtube.py", line 376, in _parse_item
    BaseChatDownloader.remap(info, YouTubeChatDownloader._REMAPPING,
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_replay_downloader\sites\common.py", line 254, in remap
    info[index] = remapping_functions[mapping_function](
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_replay_downloader\sites\youtube.py", line 502, in <lambda>
    'parse_runs': lambda x: YouTubeChatDownloader.parse_runs(x, True),
  File "C:\Users\atnbueno\AppData\Local\Programs\Python\Python310\lib\site-packages\chat_replay_downloader\sites\youtube.py", line 357, in parse_runs
    message_text += run['emoji']['shortcuts'][0]
KeyError: 'shortcuts'
```

## Expected behavior
The program should not crash

## Screenshots
N/A

## Additional context/information
The next message in the chat was "👍🏼👍🏼"

**Comment by xenova** [comment]
Hi, you are using a very old version of the program. It is now named `chat_downloader` instead of `chat_replay_downloader`. Please install it using `pip install chat_downloader --upgrade` and you can do what you want to do with:
```bash
chat_downloader -v https://www.youtube.com/watch?v=KXlgRVFHhHo -o livechat.csv
```

Let me know if that helps!

**Comment by atnbueno** [comment]
That was it. Thanks for your help and for this terribly useful tool.
