### ISSUE TITLE
[BUG] `AttributeError: 'NoneType' object has no attribute 'close'` on Twitch VODs with no messages

### ISSUE THREAD

**Issue by TheTechRobo** [xenova/chat-downloader#172]
## Basic information
- Program version: 0.2.0
- Python version: 3.9.7
- Operating system: Elive 3.8.30 (based on Debian 11)

## Describe the bug
I get this traceback when running https://www.twitch.tv/videos/298359855 with an output file :

```
Traceback (most recent call last):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 283, in __next__
    item = next(self.chat)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/chat_downloader", line 8, in <module>
    sys.exit(main())
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/cli.py", line 194, in main
    run(**args.__dict__)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/chat_downloader.py", line 360, in run
    for message in chat:
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 295, in __next__
    self._output_writer.close()
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/output/continuous_write.py", line 266, in close
    self.writer.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader -v https://www.twitch.tv/videos/298359855  -o /dev/null
```
2. Output from the above command:

<details>

```
[DEBUG] Python version: 3.9.7 (default, Oct 10 2021, 14:08:54)
[GCC 8.3.0]
[DEBUG] Program version: 0.2.0
[DEBUG] Initialisation parameters: {'headers': None, 'cookies': None, 'proxy': None}
[DEBUG] Created TwitchChatDownloader session.
[DEBUG] Starting new HTTPS connection (1): badges.twitch.tv:443
[DEBUG] https://badges.twitch.tv:443 "GET /v1/badges/global/display HTTP/1.1" 200 99033
[INFO] Site: twitch.tv
[DEBUG] Program parameters: {'url': 'https://www.twitch.tv/videos/298359855', 'start_time': None, 'end_time': None, 'max_attempts': 15, 'retry_timeout': None, 'interruptible_retry': True, 'timeout': None, 'inactivity_timeout': None, 'max_messages': None, 'message_groups': ['messages'], 'message_types': None, 'output': '/dev/null', 'overwrite': True, 'sort_keys': True, 'indent': 4, 'format': 'twitch', 'format_file': None, 'chat_type': 'live', 'ignore': None, 'message_receive_timeout': 0.1, 'buffer_size': 4096}
[DEBUG] Starting new HTTPS connection (1): gql.twitch.tv:443
[DEBUG] https://gql.twitch.tv:443 "POST /gql HTTP/1.1" 200 813
[DEBUG] https://badges.twitch.tv:443 "GET /v1/badges/channels/30865941/display HTTP/1.1" 200 17
[DEBUG] Match found: "<re.Match object; span=(0, 38), match='https://www.twitch.tv/videos/298359855'>". Running "_get_chat_by_vod_id" function in "TwitchChatDownloader".
[DEBUG] Chat information: {'chat': <generator object TwitchChatDownloader._get_chat_messages_by_vod_id at 0x7fbf17665510>, 'title': 'bc3 funny', 'duration': 138, 'status': 'past', 'video_type': 'video', 'start_time': None, 'id': '298359855', '_output_writer': <chat_downloader.output.continuous_write.ContinuousWriter object at 0x7fbf177277c0>, '_output_callback': None, 'format': <function ChatDownloader.get_chat.<locals>.<lambda> at 0x7fbf176d7d30>, 'site': <chat_downloader.sites.twitch.TwitchChatDownloader object at 0x7fbf17727eb0>}
[INFO] Retrieving chat for "bc3 funny".
[DEBUG] Starting new HTTPS connection (1): api.twitch.tv:443
[DEBUG] https://api.twitch.tv:443 "GET /v5/videos/298359855/comments?client_id=kimne78kx3ncx6brgo4mv6wki5h1ko&cursor=&content_offset_seconds=0 HTTP/1.1" 200 15
[DEBUG] Total number of messages: 0
[DEBUG] Session closed.
Traceback (most recent call last):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 283, in __next__
    item = next(self.chat)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/chat_downloader", line 8, in <module>
    sys.exit(main())
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/cli.py", line 194, in main
    run(**args.__dict__)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/chat_downloader.py", line 360, in run
    for message in chat:
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/sites/common.py", line 295, in __next__
    self._output_writer.close()
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/chat_downloader/output/continuous_write.py", line 266, in close
    self.writer.close()
AttributeError: 'NoneType' object has no attribute 'close'

```

</details>

## Expected behavior
No messages should have been written to the output file.

## Additional context/information
It seems that when there are no chat messages, this occurs?

**Comment by xenova** [comment]
Thanks for the report. This is indeed a bug 😅 

Fixing now

**Comment by TheTechRobo** [comment]
@xenova Thanks, I missed this notification. I'll test this asap!

**Comment by TheTechRobo** [comment]
Hm, does this mean if there are no messages the file won't be created?

**Comment by xenova** [comment]
> Hm, does this mean if there are no messages the file won't be created?

Yes, that is correct. This was needed otherwise if you tried to get the chat from an invalid stream/video, a file would be created. I also don't see the usefulness in just creating an empty file in these cases.

Of course, if you really need an empty file to be created, you can `touch <file_name>` or something similar.

**Comment by TheTechRobo** [comment]
Yeah, I just setup the script to write `[]` to the file beforehand.

Thanks for fixing this!
