### ISSUE TITLE
KeyError: 'shortcuts'

### ISSUE THREAD

**Issue by SplitPeas8675309** [xenova/chat-downloader#194]
## Basic information
- Program version: latest
- Python version: 3.10.6
- Operating system: Linux Lite 6.2

## Describe the bug
When running the code, an emoji is causing an error. I saw this problem in a previous bug report. 

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader https://www.youtube.com/watch?v=dwzed6ihurA
```
2. Output from the above command:
```
[output goes here]
```
... (runs normally outputting chat) ...

56:13 | (Moderator) Anarchy Princcess: No hissy. Just his phone. We will get there one day. He’s in training 

Traceback (most recent call last):
  File "/usr/local/bin/chat_replay_downloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/chat_replay_downloader/cli.py", line 229, in main
    for message in chat:
  File "/usr/local/lib/python3.10/dist-packages/chat_replay_downloader/sites/common.py", line 87, in __iter__
    for item in self.chat:
  File "/usr/local/lib/python3.10/dist-packages/chat_replay_downloader/sites/youtube.py", line 1014, in _get_chat_messages
    data = self._parse_item(original_item, data)
  File "/usr/local/lib/python3.10/dist-packages/chat_replay_downloader/sites/youtube.py", line 376, in _parse_item
    BaseChatDownloader.remap(info, YouTubeChatDownloader._REMAPPING,
  File "/usr/local/lib/python3.10/dist-packages/chat_replay_downloader/sites/common.py", line 254, in remap
    info[index] = remapping_functions[mapping_function](
  File "/usr/local/lib/python3.10/dist-packages/chat_replay_downloader/sites/youtube.py", line 502, in <lambda>
    'parse_runs': lambda x: YouTubeChatDownloader.parse_runs(x, True),
  File "/usr/local/lib/python3.10/dist-packages/chat_replay_downloader/sites/youtube.py", line 357, in parse_runs
    message_text += run['emoji']['shortcuts'][0]
KeyError: 'shortcuts'

## Screenshots
https://postimg.cc/6yRPt5m3

## Additional context/information
Might be the \m/ handsign emoji causing the problem?

**Comment by xenova** [comment]
Hi there. This was a problem in an older version of the software, so, I assume you're not running the latest version (where it has been fixed).

You can upgrade using `pip install --upgrade chat-downloader`. The current version is v0.2.3.

Let me know if you have any further questions 👍

**Comment by TheTechRobo** [comment]
Note that if the new versions are incompatible with your Python version, pip will **silently** install an older version.

**Comment by SplitPeas8675309** [comment]
@xenova @TheTechRobo There was a problem updating and that was exactly the fix. Thank you so very much!
